import { Platform, StyleSheet } from "react-native";
import { C, F, FIGMA_FRAME_HEIGHT, FIGMA_FRAME_WIDTH, glass } from "./theme";

const s = StyleSheet.create({
  nativeViewport: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    overflow: "hidden",
    backgroundColor: "#fff",
  },
  nativeFrame: {
    position: "relative",
    overflow: "hidden",
  },
  nativeCanvas: {
    position: "absolute",
    width: FIGMA_FRAME_WIDTH,
    height: FIGMA_FRAME_HEIGHT,
  },
  screenTransition: {
    flex: 1,
    minHeight: 0,
    width: Platform.OS === "web" ? FIGMA_FRAME_WIDTH : "100%",
    height: Platform.OS === "web" ? FIGMA_FRAME_HEIGHT : "100%",
    alignSelf: "center",
    overflow: "hidden",
  },
  safe: {
    flex: 1,
    height: Platform.OS === "web" ? FIGMA_FRAME_HEIGHT : "100%",
    maxHeight: Platform.OS === "web" ? FIGMA_FRAME_HEIGHT : undefined,
    minHeight: 0,
    width: Platform.OS === "web" ? FIGMA_FRAME_WIDTH : "100%",
    maxWidth: FIGMA_FRAME_WIDTH,
    marginHorizontal: "auto",
    backgroundColor: "#fff",
    overflow: "hidden",
    paddingTop: Platform.OS === "android" ? 8 : 0,
  },
  bgWhite: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "#fff",
  },
  bgCream: {
    ...StyleSheet.absoluteFill,
  },
  bgMint: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "rgba(234,248,209,.2)",
  },
  bgNoise: {
    ...StyleSheet.absoluteFill,
    opacity: 1,
  },
  glassBlur: {
    ...StyleSheet.absoluteFill,
    overflow: "hidden",
  },
  glassGradient: {
    ...StyleSheet.absoluteFill,
  },
  glassInnerEdge: {
    ...StyleSheet.absoluteFill,
    borderWidth: 0.35,
    borderColor: "rgba(255,255,255,.5)",
  },
  deviceStatusBar: { display: "none" },
  deviceStatusText: { display: "none" },
  deviceStatusTextLight: { display: "none" },
  loader: { flex: 1, alignItems: "center", justifyContent: "center" },
  screenList: { flex: 1, minHeight: 0 },
  screenScroll: { flex: 1, minHeight: 0 },
  heading: {
    height: 102,
    flexDirection: "row",
    gap: 16,
    alignItems: "center",
    paddingHorizontal: 30,
    paddingTop: 6,
  },
  headingText: { fontFamily: F.display, fontSize: 32, color: C.red },
  headerRow: {
    height: 90,
    paddingHorizontal: 27,
    paddingTop: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  iconRow: { flexDirection: "row", gap: 10, alignItems: "center" },
  headerIcon: {
    width: 25,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  headerIconActive: {
    borderRadius: 10,
    backgroundColor: "rgba(204,36,44,.1)",
  },
  filterScroller: {
    height: 45,
    minHeight: 45,
    maxHeight: 45,
    flexGrow: 0,
    flexShrink: 0,
  },
  filters: { height: 45, paddingHorizontal: 27, gap: 8, alignItems: "center" },
  exploreRecommendations: {
    width: 374,
    paddingTop: 0,
  },
  exploreRailSection: {
    marginBottom: 25,
  },
  exploreRailHeading: {
    minHeight: 44,
    marginBottom: 9,
    paddingHorizontal: 1,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 10,
  },
  exploreRailHeadingCompact: {
    minHeight: 30,
  },
  exploreRailHeadingCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  exploreRailTitle: {
    fontFamily: F.bold,
    fontSize: 16,
    color: C.ink,
  },
  exploreRailSubtitle: {
    fontFamily: F.regular,
    fontSize: 10,
    lineHeight: 14,
    color: "rgba(32,26,27,.64)",
  },
  exploreRailAction: {
    minHeight: 30,
    paddingHorizontal: 10,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "rgba(204,36,44,.32)",
    backgroundColor: "rgba(255,254,248,.7)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  exploreRailActionText: {
    fontFamily: F.bold,
    fontSize: 9,
    color: C.red,
  },
  exploreRail: {
    paddingHorizontal: 1,
    paddingVertical: 2,
    gap: 12,
  },
  pill: {
    borderWidth: 1,
    borderColor: "rgba(0,0,0,.4)",
    borderRadius: 999,
    paddingHorizontal: 13,
    paddingVertical: 6,
    alignSelf: "flex-start",
  },
  tiny: { fontFamily: F.medium, fontSize: 10, color: C.ink },
  body: { fontFamily: F.medium, fontSize: 12, lineHeight: 15, color: C.ink },
  reviewText: {
    fontFamily: F.regular,
    fontSize: 12,
    lineHeight: 15,
    color: C.ink,
  },
  cardTitle: { fontFamily: F.bold, fontSize: 14, color: C.ink },
  inline: { flexDirection: "row", alignItems: "center", gap: 8 },
  inlineText: { fontFamily: F.medium, fontSize: 12, color: C.ink },
  primary: {
    backgroundColor: C.red,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    padding: 13,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 3 },
  },
  primaryText: { fontFamily: F.bold, fontSize: 14, color: "#fff" },
  secondary: {
    ...glass,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    padding: 13,
  },
  secondaryText: { fontFamily: F.bold, fontSize: 14, color: C.teal },
  searchInput: {
    height: 38,
    marginHorizontal: 28,
    marginVertical: 4,
    borderRadius: 19,
    backgroundColor: "rgba(255,255,255,.7)",
    paddingHorizontal: 16,
    fontFamily: F.regular,
  },
  searchBar: {
    ...glass,
    height: 52,
    marginHorizontal: 32,
    borderRadius: 23,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "rgba(255,255,255,.74)",
  },
  searchField: {
    flex: 1,
    height: 48,
    fontFamily: F.medium,
    fontSize: 14,
    color: C.ink,
    outlineStyle: "none",
  } as any,
  searchModeSwitch: {
    height: 38,
    marginHorizontal: 32,
    marginBottom: 12,
    padding: 3,
    borderRadius: 19,
    backgroundColor: "rgba(43,73,89,.1)",
    flexDirection: "row",
  },
  searchModeButton: {
    flex: 1,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  searchModeButtonActive: {
    backgroundColor: C.teal,
    shadowColor: "#000",
    shadowOpacity: 0.16,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 2 },
  },
  searchModeText: {
    fontFamily: F.bold,
    fontSize: 12,
    color: C.teal,
  },
  searchModeTextActive: { color: "#fff" },
  searchCount: {
    marginHorizontal: 33,
    marginTop: 16,
    marginBottom: 8,
    fontFamily: F.bold,
    fontSize: 12,
    color: C.ink,
  },
  searchResults: { paddingHorizontal: 32, paddingBottom: 30, gap: 12 },
  searchResultCard: {
    ...glass,
    minHeight: 96,
    borderRadius: 23,
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
  },
  searchResultImageBox: {
    width: 62,
    height: 76,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  searchResultImage: { width: 62, height: 76 },
  spriteSearchImage: {
    position: "absolute",
    width: 151,
    height: 103,
    left: -28,
    top: -14,
  },
  searchResultCopy: { flex: 1, gap: 4, paddingHorizontal: 12 },
  searchResultName: { fontFamily: F.bold, fontSize: 16, color: C.ink },
  searchSaveButton: {
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,.7)",
    alignItems: "center",
    justifyContent: "center",
  },
  searchEmptyState: {
    alignItems: "center",
    marginTop: 62,
    gap: 10,
  },
  emptyTitle: { fontFamily: F.bold, fontSize: 18, color: C.ink },
  emptyPrompt: { fontFamily: F.medium, fontSize: 13, color: C.teal },
  requestDrinkButton: {
    minWidth: 148,
    height: 42,
    borderRadius: 21,
    marginTop: 4,
    backgroundColor: C.red,
    alignItems: "center",
    justifyContent: "center",
  },
  requestPageContent: {
    paddingHorizontal: 32,
    paddingTop: 18,
    paddingBottom: 40,
  },
  requestFormCard: {
    borderRadius: 26,
    padding: 24,
    backgroundColor: "rgba(255,254,248,.94)",
    alignItems: "stretch",
  },
  requestIconCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(204,36,44,.1)",
    marginBottom: 16,
  },
  requestFormTitle: {
    fontFamily: F.display,
    fontSize: 22,
    color: C.red,
    textAlign: "center",
  },
  requestFormCopy: {
    fontFamily: F.regular,
    fontSize: 12,
    lineHeight: 17,
    color: "rgba(32,26,27,.72)",
    textAlign: "center",
    marginTop: 10,
    marginBottom: 24,
  },
  requestInputLabel: {
    fontFamily: F.bold,
    fontSize: 12,
    color: C.ink,
    marginBottom: 7,
  },
  requestNameInput: {
    height: 50,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(43,73,89,.28)",
    backgroundColor: "#fff",
    paddingHorizontal: 15,
    fontFamily: F.medium,
    fontSize: 14,
    color: C.ink,
  },
  requestSubmit: { height: 46, marginTop: 18 },
  disabledButton: { opacity: 0.38 },
  requestSuccess: {
    marginTop: 16,
    padding: 13,
    borderRadius: 14,
    backgroundColor: "rgba(4,178,100,.12)",
    borderWidth: 1,
    borderColor: "rgba(4,178,100,.28)",
  },
  requestSuccessTitle: { fontFamily: F.bold, fontSize: 12, color: C.green },
  requestSuccessText: {
    fontFamily: F.regular,
    fontSize: 11,
    lineHeight: 15,
    color: C.ink,
    marginTop: 3,
  },
  profileSearchCard: {
    ...glass,
    minHeight: 76,
    borderRadius: 23,
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
  },
  profileSearchAvatar: { width: 50, height: 50, borderRadius: 25 },
  grid: {
    width: 374,
    alignSelf: "center",
    paddingTop: 20,
    paddingBottom: 130,
    gap: 22,
  },
  exploreAllGrid: {
    paddingTop: 5,
  },
  exploreBrowseAll: {
    minHeight: 26,
    paddingHorizontal: 1,
    justifyContent: "flex-end",
    marginTop: -5,
    marginBottom: -5,
  },
  gridRow: {
    width: 374,
    gap: 22,
  },
  locationOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
    backgroundColor: "rgba(32,26,27,.38)",
  },
  locationCard: {
    width: "100%",
    maxWidth: 366,
    borderRadius: 24,
    padding: 22,
    alignItems: "center",
    backgroundColor: C.cream,
    borderWidth: 1,
    borderColor: "rgba(43,73,89,.18)",
    shadowColor: C.ink,
    shadowOpacity: 0.2,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  locationTitle: {
    marginTop: 10,
    fontFamily: F.bold,
    fontSize: 18,
    color: C.ink,
    textAlign: "center",
  },
  locationCopy: {
    marginTop: 7,
    fontFamily: F.regular,
    fontSize: 11,
    lineHeight: 16,
    color: "rgba(32,26,27,.68)",
    textAlign: "center",
  },
  locationInput: {
    width: "100%",
    height: 46,
    marginTop: 18,
    borderRadius: 16,
    borderWidth: 1.2,
    borderColor: "rgba(43,73,89,.4)",
    backgroundColor: "#fff",
    paddingHorizontal: 14,
    fontFamily: F.medium,
    fontSize: 13,
    color: C.ink,
  },
  locationActions: {
    width: "100%",
    marginTop: 16,
    flexDirection: "row",
    gap: 10,
  },
  locationSecondaryButton: {
    flex: 1,
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: "rgba(43,73,89,.3)",
    alignItems: "center",
    justifyContent: "center",
  },
  locationSecondaryText: {
    fontFamily: F.bold,
    fontSize: 11,
    color: C.teal,
  },
  locationPrimaryButton: {
    flex: 1,
    height: 42,
    borderRadius: 21,
    backgroundColor: C.red,
    alignItems: "center",
    justifyContent: "center",
  },
  drinkCard: {
    width: 110,
    height: 187,
    borderRadius: 16,
    ...(Platform.OS === "android"
      ? {
          boxShadow: "0px 3px 8px rgba(0,0,0,0.25)",
        }
      : {
          shadowColor: "#000",
          shadowOpacity: 0.25,
          shadowRadius: 8,
          shadowOffset: { width: 0, height: 3 },
          elevation: 6,
        }),
  },
  drinkCardSurface: {
    flex: 1,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor:
      Platform.OS === "android"
        ? "rgba(242,249,229,.82)"
        : "rgba(255,255,255,.1)",
  },
  drinkGlow: { ...StyleSheet.absoluteFill },
  drinkImageFrame: {
    width: 110,
    height: 154,
    overflow: "hidden",
    alignItems: "center",
    paddingTop: 2,
    paddingHorizontal: 0,
  },
  drinkImage: {
    width: "110%",
    height: 150,
    backgroundColor: "transparent",
  },
  remoteDrinkImage: { mixBlendMode: "multiply" },
  spriteExploreImage: {
    position: "absolute",
    width: 424,
    height: 286,
    left: -99,
    top: -53,
  },
  drinkLabel: {
    height: 33,
    backgroundColor: "rgba(255,255,255,.8)",
    alignItems: "center",
    paddingTop: 3,
  },
  drinkName: { fontFamily: F.bold, fontSize: 11, maxWidth: 100 },
  savedMark: {
    display: "none",
    position: "absolute",
    right: 6,
    top: 5,
    color: C.red,
    fontSize: 16,
  },
  saveButton: {
    position: "absolute",
    right: 6,
    top: 6,
    width: 27,
    height: 27,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,.76)",
    alignItems: "center",
    justifyContent: "center",
  },
  nav: {
    position: "absolute",
    left: 33,
    right: 33,
    bottom: 34,
    height: 80,
    borderRadius: 24,
    borderWidth: 0.35,
    borderColor: "rgba(255,255,255,.5)",
    ...(Platform.OS === "android"
      ? {
          backgroundColor: "rgba(74,105,108,.62)",
          boxShadow: "0px 6px 6px rgba(0,0,0,0.34)",
        }
      : {
          shadowColor: "#000",
          shadowOpacity: 0.4,
          shadowRadius: 6,
          shadowOffset: { width: 0, height: 6 },
          elevation: 10,
        }),
    overflow: "hidden",
    flexDirection: "row",
  },
  navBlur: {
    ...StyleSheet.absoluteFill,
  },
  navTint: {
    ...StyleSheet.absoluteFill,
  },
  navHighlight: { ...StyleSheet.absoluteFill },
  navItem: { flex: 1, alignItems: "center", justifyContent: "center" },
  navActive: { backgroundColor: "rgba(0,0,0,.3)" },
  navText: {
    fontFamily: F.display,
    fontSize: 16,
    color: "#173746",
    textShadowColor: "rgba(255,255,255,.3)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  navTextActive: {
    color: "#fff",
    textShadowColor: "rgba(0,0,0,.24)",
  },
  listCard: {
    height: 110,
    borderRadius: 23,
    marginBottom: 12,
    ...(Platform.OS === "android"
      ? {
          boxShadow: "0px 4px 4px rgba(0,0,0,0.25)",
        }
      : {
          shadowColor: "#000",
          shadowOpacity: 0.25,
          shadowRadius: 4,
          shadowOffset: { width: 0, height: 4 },
          elevation: 5,
        }),
  },
  drinklistContent: {
    width: 374,
    alignSelf: "center",
    paddingTop: 14,
    paddingBottom: 130,
  },
  listCardSurface: {
    flex: 1,
    flexDirection: "row",
    overflow: "hidden",
    borderRadius: 23,
    borderWidth: 0.35,
    borderColor: "rgba(255,255,255,.5)",
    backgroundColor:
      Platform.OS === "android" ? "rgba(222,244,224,.8)" : "transparent",
  },
  listImageBox: {
    width: 77,
    backgroundColor: "rgba(244,250,228,.2)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  listImage: { width: 56, height: 72 },
  spriteListImage: {
    position: "absolute",
    width: 221,
    height: 149,
    left: -42,
    top: -14,
  },
  listDetails: {
    flex: 1,
    paddingTop: 7,
    paddingLeft: 12,
    paddingRight: 4,
  },
  listMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 7,
  },
  listTagsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 11,
    overflow: "hidden",
    paddingRight: 2,
  },
  listTag: {
    minWidth: 0,
    maxWidth: "32%",
    flexShrink: 1,
    borderWidth: 1,
    borderColor: "rgba(150,0,0,.54)",
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 4,
    backgroundColor: "rgba(255,119,125,.3)",
  },
  listTagText: {
    fontFamily: F.medium,
    fontSize: 9,
    lineHeight: 11,
    color: "#960000",
  },
  listActions: {
    width: 54,
    paddingTop: 16,
    paddingRight: 21,
    alignItems: "flex-end",
    gap: 11,
  },
  smallButton: {
    ...glass,
    width: 33,
    height: 33,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,.8)",
    alignItems: "center",
    justifyContent: "center",
  },
  empty: {
    fontFamily: F.medium,
    textAlign: "center",
    marginTop: 70,
    color: "#666",
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 0.5,
    borderColor: "rgba(43,73,89,.28)",
    backgroundColor: C.cream,
  },
  initialsAvatar: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.teal,
    borderWidth: 0.5,
    borderColor: "rgba(255,255,255,.75)",
    overflow: "hidden",
  },
  initialsAvatarText: {
    fontFamily: F.bold,
    color: C.cream,
    letterSpacing: 0.3,
  },
  hero: {
    ...glass,
    height: 275,
    marginHorizontal: 35,
    borderRadius: 23,
    backgroundColor: "rgba(250,255,242,.36)",
    borderColor: "rgba(4,178,100,.18)",
    position: "relative",
    overflow: "hidden",
  },
  heroImage: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 15,
    width: "100%",
    height: 240,
  },
  spriteHeroImage: {
    width: 669,
    height: 501,
    left: -52,
    right: undefined,
    top: -78,
  },
  heroPill: { position: "absolute", left: 14, top: 14, zIndex: 2 },
  detailCard: {
    ...glass,
    marginHorizontal: 32,
    marginTop: 22,
    marginBottom: 5,
    borderRadius: 23,
    padding: 21,
    overflow: "hidden",
  },
  detailMeta: { gap: 3 },
  officialTagsSection: { marginTop: 14, gap: 8 },
  officialTagsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
    width: "100%",
  },
  detailTitle: { fontFamily: F.bold, fontSize: 28, color: C.ink },
  reviewCard: {
    marginHorizontal: 32,
    marginBottom: 14,
    borderRadius: 16,
    paddingBottom: 7,
    backgroundColor: "rgba(4,178,100,.2)",
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  reviewFront: {
    minHeight: 154,
    borderRadius: 16,
    padding: 20,
    backgroundColor: C.cream,
  },
  reviewHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  reviewIdentity: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  reviewDetailContent: {
    paddingHorizontal: 32,
    paddingBottom: 130,
  },
  reviewDetailDrinkStrip: {
    height: 84,
    borderRadius: 20,
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 3 },
  },
  reviewDetailImageBox: {
    width: 52,
    height: 66,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  reviewDetailDrinkImage: { width: 48, height: 62 },
  spriteReviewDetailImage: {
    position: "absolute",
    width: 190,
    height: 128,
    left: -46,
    top: -28,
  },
  reviewDetailDrinkCopy: { flex: 1, gap: 4, marginLeft: 12 },
  reviewDetailDepth: {
    marginTop: 18,
    paddingBottom: 8,
    borderRadius: 20,
    backgroundColor: "rgba(4,178,100,.2)",
    shadowColor: "#000",
    shadowOpacity: 0.24,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 4 },
  },
  reviewDetailCard: {
    borderRadius: 20,
    padding: 22,
    backgroundColor: C.cream,
  },
  reviewDetailAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 0.5,
    borderColor: "rgba(43,73,89,.3)",
    backgroundColor: C.cream,
  },
  reviewDetailText: {
    fontFamily: F.regular,
    fontSize: 15,
    lineHeight: 21,
    color: C.ink,
    marginVertical: 22,
  },
  reviewDetailUploadedImage: {
    width: "100%",
    height: 190,
    borderRadius: 18,
    marginBottom: 18,
    backgroundColor: "rgba(255,255,255,.55)",
  },
  reviewDetailFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  reviewDetailLikeButton: {
    minWidth: 46,
    height: 32,
    paddingHorizontal: 9,
    borderRadius: 16,
    backgroundColor: "rgba(204,36,44,.08)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  reviewCommentsTitle: {
    fontFamily: F.bold,
    fontSize: 16,
    color: C.ink,
    marginTop: 26,
    marginBottom: 10,
  },
  commentCard: {
    minHeight: 72,
    borderRadius: 18,
    padding: 13,
    marginBottom: 10,
    backgroundColor: "rgba(4,178,100,.16)",
    borderWidth: 0.5,
    borderColor: "rgba(4,125,82,.28)",
    shadowColor: "#000",
    shadowOpacity: 0.14,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    flexDirection: "row",
    gap: 10,
  },
  commentAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 0.5,
    borderColor: "rgba(43,73,89,.3)",
    backgroundColor: C.cream,
  },
  commentCopy: { flex: 1, gap: 6 },
  commentUserName: { fontFamily: F.bold, fontSize: 12, color: C.teal },
  commentHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  reviewNoComments: {
    fontFamily: F.medium,
    fontSize: 12,
    color: "rgba(32,26,27,.58)",
    marginBottom: 12,
  },
  commentComposer: {
    minHeight: 54,
    borderRadius: 21,
    padding: 6,
    paddingLeft: 14,
    marginTop: 8,
    backgroundColor: "rgba(255,254,248,.94)",
    borderWidth: 0.5,
    borderColor: "rgba(43,73,89,.3)",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  commentInput: {
    flex: 1,
    height: 42,
    fontFamily: F.medium,
    fontSize: 12,
    color: C.ink,
    outlineStyle: "none",
  } as any,
  commentSubmit: {
    minWidth: 68,
    height: 42,
    borderRadius: 18,
    backgroundColor: C.red,
    alignItems: "center",
    justifyContent: "center",
  },
  commentSubmitDisabled: {
    opacity: 1,
    backgroundColor: "rgba(204,36,44,.72)",
  },
  reviewDrink: {
    height: 99,
    marginHorizontal: 33,
    marginTop: 10,
    borderRadius: 23,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 15,
  },
  reviewDrinkCopy: {
    flex: 1,
    minWidth: 0,
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 6,
  },
  reviewDrinkTitle: {
    width: "100%",
    flexShrink: 1,
    fontFamily: F.bold,
    fontSize: 20,
    lineHeight: 24,
    color: C.ink,
  },
  reviewDrinkImageBox: {
    width: 55,
    height: 76,
    marginRight: 8,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  reviewDrinkImage: { width: 55, height: 76 },
  spriteReviewImage: {
    position: "absolute",
    width: 212,
    height: 159,
    left: -48,
    top: -30,
  },
  ratingCard: {
    height: 100,
    margin: 22,
    marginHorizontal: 33,
    borderRadius: 23,
    padding: 20,
    gap: 10,
  },
  ratingRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  starPicker: { flexDirection: "row", alignItems: "center", gap: 2 },
  halfStarFill: {
    position: "absolute",
    left: 0,
    top: 0,
    height: 35,
    overflow: "hidden",
  },
  filledStar: { position: "absolute", left: 0, top: 0 },
  halfStarHitArea: {
    ...StyleSheet.absoluteFill,
    flexDirection: "row",
  },
  halfStarButton: { flex: 1 },
  ratingNumber: { fontFamily: F.bold, fontSize: 36, color: C.ink },
  formCard: {
    minHeight: 264,
    marginHorizontal: 33,
    borderRadius: 23,
    padding: 12,
  },
  reviewInput: {
    height: 209,
    marginTop: 8,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,.8)",
    padding: 12,
    fontFamily: F.regular,
    fontSize: 12,
  },
  notesCard: {
    margin: 22,
    marginHorizontal: 33,
    borderRadius: 23,
    padding: 20,
  },
  customNoteRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 10,
  },
  customNoteInput: {
    flex: 1,
    height: 30,
    borderRadius: 15,
    paddingHorizontal: 12,
    backgroundColor: "rgba(255,255,255,.52)",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,.25)",
    fontFamily: F.medium,
    fontSize: 10,
  },
  addNoteButton: {
    height: 28,
    minWidth: 62,
    borderRadius: 14,
    paddingHorizontal: 13,
    backgroundColor: C.teal,
    alignItems: "center",
    justifyContent: "center",
  },
  notes: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 12 },
  noteChip: {
    height: 24,
    minWidth: 65,
    paddingHorizontal: 13,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "rgba(43,73,89,.55)",
    alignItems: "center",
    justifyContent: "center",
  },
  noteChipSelected: {
    backgroundColor: "rgba(255,119,125,.3)",
    borderColor: "rgba(150,0,0,.54)",
  },
  addNoteChip: {
    height: 24,
    minWidth: 65,
    paddingHorizontal: 13,
    borderRadius: 15,
    backgroundColor: C.teal,
    alignItems: "center",
    justifyContent: "center",
  },
  commonTagsSection: {
    marginHorizontal: 32,
    marginBottom: 14,
    paddingHorizontal: 2,
    gap: 6,
  },
  userFlavourTagsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 2,
  },
  reviewPromptTextWrap: {
    marginHorizontal: 52,
    marginBottom: 18,
    gap: 7,
  },
  reviewPromptTitle: {
    fontFamily: F.bold,
    fontSize: 15,
    color: C.ink,
  },
  reviewPromptCopy: {
    fontFamily: F.regular,
    fontSize: 12,
    lineHeight: 17,
    color: "rgba(32,26,27,.72)",
  },
  commonTagsText: {
    fontFamily: F.medium,
    fontSize: 12,
    lineHeight: 18,
    color: "#960000",
  },
  profileCard: {
    width: 374,
    height: 77,
    alignSelf: "center",
    marginTop: 21,
    borderRadius: 23,
    paddingHorizontal: 20,
    paddingVertical: 11,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    overflow: "hidden",
  },
  profileAvatar: { width: 55, height: 55, borderRadius: 28 },
  profileDetails: {
    flex: 1,
    height: 55,
    justifyContent: "center",
    gap: 2,
  },
  profileHandle: {
    fontFamily: F.bold,
    fontSize: 10,
    lineHeight: 11,
    color: C.ink,
  },
  profileEditWrap: {
    height: 55,
    justifyContent: "center",
    alignItems: "center",
  },
  profileAction: {
    minWidth: 44,
    height: 29,
    paddingHorizontal: 7,
    borderRadius: 10,
    borderWidth: 1.3,
    borderColor: "rgba(4,178,100,.3)",
    backgroundColor: "rgba(4,178,100,.1)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  profileActionFollowing: {
    backgroundColor: C.green,
    borderColor: C.green,
  },
  profileActionText: {
    fontFamily: F.medium,
    fontSize: 12,
    lineHeight: 15,
    color: C.green,
  },
  profileActionTextFollowing: { color: C.cream },
  profileTabs: {
    width: 374,
    alignSelf: "center",
  },
  profilePageContent: {
    paddingBottom: 210,
  },
  settingsContent: { paddingHorizontal: 32, paddingBottom: 40 },
  settingsDetailContent: { paddingHorizontal: 32, paddingBottom: 40 },
  settingsDetailCard: {
    borderRadius: 23,
    padding: 20,
    overflow: "hidden",
  },
  settingsDetailTitle: {
    fontFamily: F.bold,
    fontSize: 18,
    color: C.ink,
    marginBottom: 7,
  },
  settingsDetailCopy: {
    fontFamily: F.regular,
    fontSize: 12,
    lineHeight: 18,
    color: "rgba(32,26,27,.72)",
    marginBottom: 18,
  },
  settingsInputLabel: {
    fontFamily: F.bold,
    fontSize: 11,
    color: C.ink,
    marginBottom: 6,
  },
  settingsInput: {
    height: 48,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(43,73,89,.2)",
    backgroundColor: "rgba(255,254,248,.92)",
    paddingHorizontal: 14,
    marginBottom: 14,
    fontFamily: F.medium,
    fontSize: 13,
    color: C.ink,
    outlineStyle: "none",
  } as any,
  settingsVerifiedRow: {
    alignSelf: "flex-start",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "rgba(4,178,100,.1)",
    marginBottom: 18,
  },
  settingsVerifiedText: {
    fontFamily: F.bold,
    fontSize: 10,
    color: C.green,
  },
  settingsPrimaryButton: {
    height: 46,
    borderRadius: 18,
    backgroundColor: C.red,
    alignItems: "center",
    justifyContent: "center",
  },
  settingsDataSummary: {
    borderRadius: 16,
    padding: 14,
    gap: 7,
    backgroundColor: "rgba(255,254,248,.78)",
    borderWidth: 1,
    borderColor: "rgba(43,73,89,.1)",
    marginBottom: 14,
  },
  settingsSecondaryButton: {
    height: 46,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(43,73,89,.24)",
    backgroundColor: "rgba(255,254,248,.78)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    marginBottom: 10,
  },
  settingsSecondaryText: {
    fontFamily: F.bold,
    fontSize: 12,
    color: C.teal,
  },
  settingsDeleteButton: {
    height: 46,
    borderRadius: 16,
    backgroundColor: "rgba(204,36,44,.09)",
    alignItems: "center",
    justifyContent: "center",
  },
  settingsDeleteText: { fontFamily: F.bold, fontSize: 12, color: C.red },
  settingsPhotoButton: {
    minHeight: 42,
    marginTop: 12,
    marginBottom: 2,
    paddingHorizontal: 16,
    borderRadius: 21,
    borderWidth: 0.75,
    borderColor: "rgba(43,73,89,.35)",
    backgroundColor: "rgba(255,255,255,.68)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  settingsAccountCard: {
    height: 82,
    borderRadius: 23,
    paddingHorizontal: 15,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  settingsAvatar: { width: 55, height: 55, borderRadius: 28 },
  settingsAccountCopy: { flex: 1, gap: 5, justifyContent: "center" },
  settingsSectionTitle: {
    fontFamily: F.bold,
    fontSize: 12,
    color: C.ink,
    marginTop: 22,
    marginBottom: 8,
  },
  settingsGroup: {
    backgroundColor: "rgba(255,254,248,.86)",
    borderRadius: 20,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(43,73,89,.12)",
  },
  settingsOption: {
    minHeight: 72,
    paddingHorizontal: 14,
    paddingVertical: 11,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(43,73,89,.12)",
  },
  settingsDangerOption: { borderBottomWidth: 0 },
  settingsOptionIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(43,73,89,.08)",
  },
  settingsDangerIcon: { backgroundColor: "rgba(204,36,44,.08)" },
  settingsOptionCopy: { flex: 1, gap: 3 },
  settingsOptionTitle: { fontFamily: F.bold, fontSize: 13, color: C.ink },
  settingsOptionSubtitle: {
    fontFamily: F.regular,
    fontSize: 10,
    lineHeight: 13,
    color: "rgba(32,26,27,.62)",
  },
  tab: {
    ...glass,
    height: 34,
    flex: 1,
    marginTop: 10,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  tabActive: { backgroundColor: C.red },
  progressCard: {
    width: 374,
    height: 66,
    marginVertical: 12,
    alignSelf: "center",
    borderRadius: 20,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  progressCircle: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  progressText: {
    position: "absolute",
    fontFamily: F.medium,
    fontSize: 10,
    color: C.ink,
  },
  badges: {
    width: 374,
    alignSelf: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    columnGap: 8,
    rowGap: 0,
  },
  badgeItem: {
    width: "31%",
    height: 120,
    alignItems: "center",
  },
  badgeLocked: { opacity: 0.42 },
  badgeLabel: {
    width: 105,
    textAlign: "center",
    marginTop: 2,
  },
  badgeComposite: { width: 88, height: 105 },
  badgeCompositeTall: { width: 88, height: 121 },
  stats: {
    width: 374,
    alignSelf: "center",
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
  },
  statsThree: { gap: 8 },
  stat: {
    height: 88,
    flex: 1,
    minWidth: 0,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    backgroundColor:
      Platform.OS === "android" ? "rgba(222,244,224,.78)" : "transparent",
    ...(Platform.OS === "android"
      ? {
          boxShadow: "0px 4px 4px rgba(0,0,0,0.25)",
        }
      : {
          shadowColor: "#000",
          shadowOpacity: 0.25,
          shadowRadius: 4,
          shadowOffset: { width: 0, height: 4 },
          elevation: 5,
        }),
  },
  statNumber: { fontFamily: F.bold, fontSize: 25 },
  statThree: { flex: 1 },
  receiptWrap: {
    width: 374,
    alignSelf: "center",
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 3 },
  },
  receipt: {
    width: "100%",
    minHeight: 405,
    backgroundColor: C.cream,
    padding: 20,
    position: "relative",
  },
  receiptItem: { marginTop: 16, paddingBottom: 16 },
  receiptItemDivider: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(32,26,27,.12)",
  },
  receiptItemCopy: { flex: 1, minWidth: 0, gap: 2 },
  receiptDrinkTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  receiptDrinkNameButton: {
    minWidth: 0,
    flexShrink: 1,
  },
  receiptEditButton: {
    width: 24,
    height: 24,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(204,36,44,.07)",
  },
  receiptReviewText: {
    fontFamily: F.regular,
    fontSize: 12,
    lineHeight: 15,
    color: C.ink,
    marginLeft: 30,
    marginTop: 5,
  },
  receiptRating: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    gap: 5,
  },
  receiptStars: { color: "#e3a000", fontSize: 12 },
  receiptRatingNumber: {
    fontFamily: F.bold,
    fontSize: 10,
    color: "rgba(32,26,27,.62)",
  },
  receiptShareButton: {
    position: "absolute",
    right: 14,
    top: 14,
    height: 30,
    paddingHorizontal: 10,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "rgba(204,36,44,.4)",
    backgroundColor: "rgba(204,36,44,.08)",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    zIndex: 2,
  },
  receiptShareText: { fontFamily: F.bold, fontSize: 10, color: C.red },
  receiptHeading: {
    width: 374,
    alignSelf: "center",
    marginVertical: 12,
  },
  receiptEmpty: {
    minHeight: 225,
    paddingHorizontal: 26,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  receiptEmptyTitle: {
    fontFamily: F.bold,
    fontSize: 15,
    color: C.ink,
    textAlign: "center",
  },
  receiptEmptyCopy: {
    maxWidth: 245,
    fontFamily: F.regular,
    fontSize: 12,
    lineHeight: 17,
    color: "rgba(32,26,27,.65)",
    textAlign: "center",
  },
  receiptEmptyButton: {
    minWidth: 132,
    minHeight: 40,
    marginTop: 6,
    paddingHorizontal: 18,
    borderRadius: 20,
    backgroundColor: C.red,
    alignItems: "center",
    justifyContent: "center",
  },
  receiptLogo: {
    fontFamily: F.display,
    fontSize: 18,
    textAlign: "center",
    marginVertical: 16,
  },
  dash: {
    borderTopWidth: 1,
    borderStyle: "dashed",
    borderColor: "#ddd",
    marginBottom: 16,
  },
  feedContent: { paddingBottom: 80 },
  feedSectionHeader: {
    marginHorizontal: 32,
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  feedMoreButton: {
    minHeight: 28,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
  },
  feedMoreArrowExpanded: { transform: [{ rotate: "180deg" }] },
  friendStrip: {
    paddingHorizontal: 32,
    gap: 2,
    marginTop: 12,
  },
  friendDrink: { width: 77, alignItems: "center" },
  friendComposite: { width: 77, height: 120 },
  friendCompactCard: {
    width: 77,
    height: 120,
    borderRadius: 9,
    ...(Platform.OS === "android"
      ? {
          boxShadow: "0px 3px 5px rgba(0,0,0,0.25)",
        }
      : {
          shadowColor: "#000",
          shadowOpacity: 0.25,
          shadowRadius: 5,
          shadowOffset: { width: 0, height: 3 },
          elevation: 5,
        }),
  },
  friendCompactSurface: {
    flex: 1,
    borderRadius: 9,
    overflow: "hidden",
    backgroundColor:
      Platform.OS === "android"
        ? "rgba(242,249,229,.86)"
        : "rgba(255,255,255,.1)",
  },
  friendCompactImageFrame: {
    width: 77,
    height: 92,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingTop: 5,
  },
  friendCompactImage: {
    width: "85%",
    height: "82%",
    backgroundColor: "transparent",
  },
  friendCompactLabel: {
    width: 77,
    height: 28,
    paddingHorizontal: 3,
    paddingTop: 2,
    backgroundColor: "rgba(255,255,255,.8)",
    alignItems: "center",
  },
  friendCompactName: {
    maxWidth: 71,
    fontFamily: F.bold,
    fontSize: 7,
    lineHeight: 9,
    textAlign: "center",
  },
  friendCompactType: {
    maxWidth: 71,
    fontFamily: F.medium,
    fontSize: 6.5,
    lineHeight: 8,
    textAlign: "center",
  },
  friendCount: {
    fontFamily: F.medium,
    fontSize: 10,
    color: C.ink,
  },
  friendSocialRow: {
    minHeight: 13,
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  friendAvatarStack: { flexDirection: "row", alignItems: "center" },
  friendMiniAvatar: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 0.35,
    borderColor: C.cream,
  },
  friendMiniAvatarOverlap: { marginLeft: -4.5 },
  activityTitle: {
    fontFamily: F.bold,
    fontSize: 14,
    color: C.ink,
    marginHorizontal: 32,
    marginTop: 29,
  },
  activityGroup: {
    fontFamily: F.regular,
    fontSize: 12,
    lineHeight: 15,
    color: C.ink,
    marginHorizontal: 33,
    marginTop: 5,
  },
  activity: {
    marginHorizontal: 33,
    marginTop: 10,
    borderRadius: 23,
    paddingHorizontal: 21,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  activityTall: { height: 66 },
  activityShort: { height: 55 },
  activityAvatar: {
    width: 33,
    height: 33,
    borderRadius: 17,
  },
  activityCopy: { flex: 1 },
  activityAction: {
    fontFamily: F.medium,
    fontSize: 10,
    color: C.red,
    marginTop: 1,
  },
  activityQuote: {
    fontFamily: F.regular,
    fontStyle: "italic",
    color: C.ink,
  },
  activityTime: {
    fontFamily: F.regular,
    fontSize: 10,
    color: "rgba(0,0,0,.7)",
  },
  feedEmptySection: {
    marginHorizontal: 32,
    paddingHorizontal: 20,
    minHeight: 72,
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 4,
  },
  feedEmptyActivity: {
    marginHorizontal: 32,
    marginTop: 12,
    minHeight: 118,
    padding: 20,
    borderRadius: 22,
    backgroundColor: "rgba(255,254,248,.42)",
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 6,
  },
  feedEmptyTitle: {
    fontFamily: F.bold,
    fontSize: 13,
    color: C.ink,
    textAlign: "left",
  },
  feedEmptyCopy: {
    maxWidth: 280,
    fontFamily: F.regular,
    fontSize: 11,
    lineHeight: 16,
    color: "rgba(32,26,27,.65)",
    textAlign: "left",
  },
  suggestedProfilesTitle: {
    marginHorizontal: 32,
    marginTop: 22,
    marginBottom: 10,
    fontFamily: F.bold,
    fontSize: 14,
    color: C.ink,
  },
  suggestedProfilesList: {
    marginHorizontal: 32,
    gap: 10,
  },
  suggestedProfileCard: {
    minHeight: 70,
    borderRadius: 18,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    overflow: "hidden",
  },
  suggestedProfileIdentity: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  suggestedProfileCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  suggestedFollowButton: {
    height: 32,
    paddingHorizontal: 12,
    borderRadius: 16,
    backgroundColor: C.green,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  suggestedFollowText: {
    fontFamily: F.bold,
    fontSize: 10,
    color: C.cream,
  },
  confirmOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
    backgroundColor: "rgba(32,26,27,.38)",
  },
  logoutConfirmCard: {
    width: "100%",
    maxWidth: 360,
    borderRadius: 24,
    padding: 24,
    backgroundColor: C.cream,
    borderWidth: 1,
    borderColor: "rgba(43,73,89,.14)",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  logoutConfirmTitle: {
    fontFamily: F.display,
    fontSize: 20,
    color: C.red,
    textAlign: "center",
  },
  logoutConfirmCopy: {
    marginTop: 10,
    fontFamily: F.regular,
    fontSize: 13,
    color: C.ink,
    textAlign: "center",
  },
  logoutConfirmActions: {
    marginTop: 22,
    flexDirection: "row",
    gap: 10,
  },
  logoutCancelButton: {
    flex: 1,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(43,73,89,.28)",
    backgroundColor: "rgba(255,255,255,.72)",
  },
  logoutConfirmButton: {
    flex: 1,
    height: 44,
    borderRadius: 22,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    backgroundColor: C.red,
  },
  oauthConsentScroll: { flex: 1 },
  oauthConsentContent: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 30,
    paddingVertical: 44,
  },
  oauthBrand: {
    fontFamily: F.display,
    fontSize: 30,
    color: C.red,
    marginBottom: 22,
  },
  oauthConsentCard: {
    width: "100%",
    minHeight: 260,
    overflow: "hidden",
    borderRadius: 24,
    padding: 24,
    justifyContent: "center",
    backgroundColor:
      Platform.OS === "android" ? "rgba(236,248,224,.9)" : "transparent",
  },
  oauthClientLogo: {
    width: 58,
    height: 58,
    alignSelf: "center",
    borderRadius: 14,
    marginBottom: 16,
    backgroundColor: "transparent",
  },
  oauthConsentTitle: {
    fontFamily: F.bold,
    fontSize: 19,
    color: C.ink,
    textAlign: "center",
  },
  oauthConsentCopy: {
    fontFamily: F.regular,
    fontSize: 13,
    lineHeight: 19,
    color: "rgba(32,26,27,.72)",
    textAlign: "center",
    marginTop: 9,
    marginBottom: 18,
  },
  oauthScopeList: {
    gap: 10,
    marginBottom: 17,
  },
  oauthScopeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  oauthScopeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: C.green,
  },
  oauthScopeText: {
    flex: 1,
    fontFamily: F.medium,
    fontSize: 12,
    color: C.ink,
  },
  oauthRedirectText: {
    fontFamily: F.regular,
    fontSize: 9,
    lineHeight: 13,
    color: "rgba(32,26,27,.5)",
    textAlign: "center",
    marginBottom: 18,
  },
  oauthConsentActions: { flexDirection: "row", gap: 10 },
  oauthDenyButton: {
    flex: 1,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: C.red,
    backgroundColor: "rgba(255,255,255,.62)",
  },
  oauthDenyText: { fontFamily: F.bold, fontSize: 12, color: C.red },
  oauthApproveButton: { flex: 1.5, height: 42 },
  oauthError: {
    fontFamily: F.medium,
    fontSize: 11,
    lineHeight: 16,
    color: C.red,
    textAlign: "center",
    marginTop: 14,
  },
  modalWrap: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,.2)",
  },
  onboard: {
    width: "100%",
    maxWidth: FIGMA_FRAME_WIDTH,
    backgroundColor: "#fffef8",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingHorizontal: 28,
    paddingTop: 16,
    paddingBottom: 24,
    gap: 10,
    overflow: "hidden",
    alignItems: "center",
  },
  createAccountScreen: {
    flex: 1,
    width: "100%",
    backgroundColor: "#fffef8",
  },
  createAccountContent: {
    width: "100%",
    maxWidth: FIGMA_FRAME_WIDTH,
    minHeight: "100%",
    alignSelf: "center",
    paddingHorizontal: 28,
    paddingTop: 24,
    paddingBottom: 36,
    alignItems: "center",
    gap: 12,
  },
  createAccountTitle: {
    width: "100%",
    marginBottom: 2,
    fontFamily: F.display,
    fontSize: 26,
    color: C.red,
    textAlign: "center",
  },
  createAvatarButton: {
    width: 88,
    height: 88,
    marginTop: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  createAvatarCamera: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: C.red,
    borderWidth: 2,
    borderColor: "#fffef8",
    alignItems: "center",
    justifyContent: "center",
  },
  createAvatarHint: {
    marginTop: -7,
    fontFamily: F.medium,
    fontSize: 10,
    color: "rgba(32,26,27,.58)",
  },
  createNameRow: {
    width: "100%",
    flexDirection: "row",
    gap: 10,
  },
  createNameInput: { flex: 1, width: undefined },
  createAccountInput: {
    color: C.ink,
    backgroundColor: "#ffffff",
    borderWidth: 1.2,
    borderColor: "rgba(43,73,89,.42)",
    shadowColor: C.ink,
    shadowOpacity: 0.08,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  handle: {
    width: 46,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#aaa",
    alignSelf: "center",
  },
  onboardTitle: {
    fontFamily: F.display,
    fontSize: 20,
    color: C.red,
    marginTop: 2,
    width: "100%",
    textAlign: "center",
  },
  onboardAge: {
    width: "100%",
    fontFamily: F.bold,
    fontSize: 14,
    color: C.ink,
    textAlign: "center",
  },
  onboardCopy: {
    width: "100%",
    fontFamily: F.regular,
    fontSize: 11,
    lineHeight: 15,
    color: "rgba(32,26,27,.72)",
    marginBottom: 2,
    textAlign: "center",
  },
  socialButton: {
    width: "100%",
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(43,73,89,.25)",
    backgroundColor: "rgba(255,255,255,.82)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  socialButtonDark: { backgroundColor: C.ink, borderColor: C.ink },
  socialButtonText: { fontFamily: F.bold, fontSize: 13, color: C.ink },
  createAccountButton: {
    width: "100%",
    height: 42,
    borderRadius: 21,
    borderWidth: 1.5,
    borderColor: C.red,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  createAccountText: { fontFamily: F.bold, fontSize: 13, color: C.red },
  onboardControl: { width: "100%" },
  textButton: {
    width: "100%",
    height: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  textButtonText: { fontFamily: F.medium, fontSize: 11, color: C.teal },
  input: {
    width: "100%",
    height: 44,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,.8)",
    paddingHorizontal: 15,
    fontFamily: F.regular,
  },
  birthDateField: {
    width: "100%",
    gap: 5,
  },
  birthDateLabel: {
    paddingLeft: 4,
    fontFamily: F.bold,
    fontSize: 11,
    color: C.ink,
  },
  birthDateInput: {
    width: "100%",
    height: 44,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,.8)",
    paddingHorizontal: 15,
    fontFamily: F.regular,
    color: C.ink,
  },
  authNotice: {
    width: "100%",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: "rgba(4,178,100,.12)",
    borderWidth: 0.5,
    borderColor: "rgba(4,178,100,.35)",
  },
  authNoticeText: {
    fontFamily: F.medium,
    fontSize: 10,
    lineHeight: 14,
    color: C.teal,
    textAlign: "center",
  },
  authNoticeError: {
    backgroundColor: "rgba(204,36,44,.1)",
    borderColor: "rgba(204,36,44,.32)",
  },
  authNoticeTextError: {
    color: C.red,
  },
  splash: {
    flex: 1,
    height: Platform.OS === "web" ? FIGMA_FRAME_HEIGHT : "100%",
    maxHeight: FIGMA_FRAME_HEIGHT,
    minHeight: 0,
    width: Platform.OS === "web" ? FIGMA_FRAME_WIDTH : "100%",
    maxWidth: FIGMA_FRAME_WIDTH,
    marginHorizontal: "auto",
    backgroundColor: "#f30",
    overflow: "hidden",
  },
  splashImage: {
    ...StyleSheet.absoluteFill,
    width: "100%",
    height: "100%",
    ...(Platform.OS === "web"
      ? ({ objectFit: "cover", objectPosition: "center top" } as any)
      : {}),
  },
  splashShade: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "rgba(255,50,0,.06)",
  },
  splashTitle: {
    position: "absolute",
    left: 0,
    right: 0,
    top: "30%",
    fontFamily: F.display,
    fontSize: 52,
    color: "#e9fae8",
    textAlign: "center",
  },
});

export default s;
