with catalogue as (
  select *
  from jsonb_to_recordset(
    $saturated_catalogue$[
      {
        "id": "absolut-vodka-original",
        "name": "Absolut Vodka Original",
        "category": "Other",
        "subtype": "Vodka",
        "brand": "Absolut",
        "origin": "Åhus, Sweden",
        "description": "A clean Swedish vodka with a rich, full-bodied character, smooth grain notes and a subtle hint of dried fruit.",
        "image_url": "https://www.absolut.com/cdn-cgi/image/format=auto,quality=85,width=1000/wp-content/uploads/Container-VODKA.jpg",
        "official_tags": ["clean", "smooth", "grain", "mellow", "dried fruit", "full-bodied"],
        "flavour_source_url": "https://www.absolut.com/en/products/absolut-vodka/",
        "origin_source_url": "https://www.absolut.com/en/absolut-collaborations/the-absolut-distillery/",
        "image_source_url": "https://www.absolut.com/en/products/absolut-vodka/",
        "catalogue_source": "Vodka and Rum",
        "catalogue_number": 104,
        "is_published": true
      },
      {
        "id": "absolut-citron",
        "name": "Absolut Citron",
        "category": "Other",
        "subtype": "Vodka",
        "brand": "Absolut",
        "origin": "Åhus, Sweden",
        "description": "A lemon-flavoured Swedish vodka with bright citrus, fresh lemon peel and a clean, smooth finish.",
        "image_url": "https://www.absolut.com/cdn-cgi/image/format=auto,quality=85,width=1000/wp-content/uploads/Container-CITRON-1.jpg",
        "official_tags": ["lemon", "citrus", "fresh", "zesty", "smooth", "clean"],
        "flavour_source_url": "https://www.absolut.com/en/products/absolut-citron/",
        "origin_source_url": "https://www.absolut.com/en/absolut-collaborations/the-absolut-distillery/",
        "image_source_url": "https://www.absolut.com/en/products/absolut-citron/",
        "catalogue_source": "Vodka and Rum",
        "catalogue_number": 105,
        "is_published": true
      },
      {
        "id": "absolut-passionfruit",
        "name": "Absolut Passionfruit",
        "category": "Other",
        "subtype": "Vodka",
        "brand": "Absolut",
        "origin": "Åhus, Sweden",
        "description": "An aromatic passionfruit-flavoured vodka with tropical fruit, orange blossom, orange and tangerine notes.",
        "image_url": "https://www.absolut.com/cdn-cgi/image/format=auto,quality=85,width=1000/wp-content/uploads/brush-background_absolut-passionfruit_16x8.jpg",
        "official_tags": ["passionfruit", "tropical", "aromatic", "orange blossom", "orange", "tangerine"],
        "flavour_source_url": "https://www.absolut.com/en/products/absolut-passionfruit/",
        "origin_source_url": "https://www.absolut.com/en/absolut-collaborations/the-absolut-distillery/",
        "image_source_url": "https://www.absolut.com/en/products/absolut-passionfruit/",
        "catalogue_source": "Vodka and Rum",
        "catalogue_number": 106,
        "is_published": true
      },
      {
        "id": "absolut-vanilia",
        "name": "Absolut Vanilia",
        "category": "Other",
        "subtype": "Vodka",
        "brand": "Absolut",
        "origin": "Åhus, Sweden",
        "description": "A creamy vanilla-flavoured vodka with bourbon vanilla, toffee, caramel and a hint of dark chocolate.",
        "image_url": "https://www.absolut.com/cdn-cgi/image/format=auto,quality=85,width=1000/wp-content/uploads/Container-VANILIA.jpg",
        "official_tags": ["vanilla", "creamy", "toffee", "caramel", "dark chocolate", "warm"],
        "flavour_source_url": "https://www.absolut.com/en/products/absolut-vanilia/",
        "origin_source_url": "https://www.absolut.com/en/absolut-collaborations/the-absolut-distillery/",
        "image_source_url": "https://www.absolut.com/en/products/absolut-vanilia/",
        "catalogue_source": "Vodka and Rum",
        "catalogue_number": 107,
        "is_published": true
      },
      {
        "id": "absolut-raspberri",
        "name": "Absolut Raspberri",
        "category": "Other",
        "subtype": "Vodka",
        "brand": "Absolut",
        "origin": "Åhus, Sweden",
        "description": "A raspberry-flavoured vodka balancing sweet and tart wild raspberry with mixed berries and soft vanilla nuances.",
        "image_url": "https://www.absolut.com/cdn-cgi/image/fit=cover,format=auto,height=1000,quality=85,width=1000/wp-content/uploads/product_absolut-raspberri_atlas_global_1x1.jpg",
        "official_tags": ["raspberry", "sweet", "tart", "wild berries", "vanilla", "fruity"],
        "flavour_source_url": "https://www.absolut.com/en-us/products/absolut-raspberri/",
        "origin_source_url": "https://www.absolut.com/en/absolut-collaborations/the-absolut-distillery/",
        "image_source_url": "https://www.absolut.com/en-us/products/absolut-raspberri/",
        "catalogue_source": "Vodka and Rum",
        "catalogue_number": 108,
        "is_published": true
      },
      {
        "id": "smirnoff-no-21-classic-vodka",
        "name": "Smirnoff No. 21 Classic Vodka",
        "category": "Other",
        "subtype": "Vodka",
        "brand": "Smirnoff",
        "origin": "Moscow, Russia",
        "description": "A triple-distilled vodka filtered ten times for essential smoothness and a clean, dry finish.",
        "image_url": "https://images.ctfassets.net/tlircn1cnxbm/615nBEJnxQru7OPdgmfVJm/33c72f45903c5afdd9dc763ba9656d48/11667547_gb-classic-vodka-red-no-21-mobile.jpg",
        "official_tags": ["smooth", "clean", "dry", "neutral", "crisp"],
        "flavour_source_url": "https://www.smirnoff.com/en",
        "origin_source_url": "https://www.smirnoff.com/en/about-us",
        "image_source_url": "https://www.smirnoff.com/en",
        "catalogue_source": "Vodka and Rum",
        "catalogue_number": 109,
        "is_published": true
      },
      {
        "id": "smirnoff-raspberry-crush",
        "name": "Smirnoff Raspberry Crush",
        "category": "Other",
        "subtype": "Vodka",
        "brand": "Smirnoff",
        "origin": "United Kingdom",
        "description": "A juicy raspberry-flavoured spirit with natural fruit flavour, bright sweetness and a smooth berry finish.",
        "image_url": "https://images.ctfassets.net/tlircn1cnxbm/6Oi2rZeXH3rfq6h5sv1wAc/4bd03a69d28b3673cf894997d64fe9fc/Raspberry_Crush_wide_-_rescale.jpg",
        "official_tags": ["raspberry", "juicy", "sweet", "smooth", "fruity"],
        "flavour_source_url": "https://www.smirnoff.com/en-gb/products/vodkas-and-flavours/raspberry-crush",
        "origin_source_url": "https://www.smirnoff.com/en-gb/about-us",
        "image_source_url": "https://www.smirnoff.com/en-gb/products/vodkas-and-flavours/raspberry-crush",
        "catalogue_source": "Vodka and Rum",
        "catalogue_number": 110,
        "is_published": true
      },
      {
        "id": "smirnoff-mango-passionfruit-twist",
        "name": "Smirnoff Mango & Passionfruit Twist",
        "category": "Other",
        "subtype": "Vodka",
        "brand": "Smirnoff",
        "origin": "United Kingdom",
        "description": "A bold tropical spirit made with natural fruit flavour, combining juicy mango and aromatic passionfruit.",
        "image_url": "https://images.ctfassets.net/tlircn1cnxbm/mjdCedwxxnseCuMZ6AL03/cdc5c970b6ef9bc034ff349c42c29e14/Mango___Passionfruit_wide_-_rescale.jpg",
        "official_tags": ["mango", "passionfruit", "tropical", "juicy", "bold", "fruity"],
        "flavour_source_url": "https://www.smirnoff.com/en-gb/products/vodkas-and-flavours/mango-passionfruit-twist",
        "origin_source_url": "https://www.smirnoff.com/en-gb/about-us",
        "image_source_url": "https://www.smirnoff.com/en-gb/products/vodkas-and-flavours/mango-passionfruit-twist",
        "catalogue_source": "Vodka and Rum",
        "catalogue_number": 111,
        "is_published": true
      },
      {
        "id": "smirnoff-cherry-drop",
        "name": "Smirnoff Cherry Drop",
        "category": "Other",
        "subtype": "Vodka",
        "brand": "Smirnoff",
        "origin": "United Kingdom",
        "description": "A cherry-flavoured spirit infused with natural juicy cherry flavour and a sweet, tangy finish.",
        "image_url": "https://images.ctfassets.net/tlircn1cnxbm/2rpFjzVr4zxraJwjlKJSIx/1ddab8dd5dd8cbb676490fe7138ad0ac/Cherry_Drop_Wide_-_rescale.jpg",
        "official_tags": ["cherry", "juicy", "sweet", "tangy", "fruity"],
        "flavour_source_url": "https://www.smirnoff.com/en-gb/products/vodkas-and-flavors/cherry-drop",
        "origin_source_url": "https://www.smirnoff.com/en-gb/about-us",
        "image_source_url": "https://www.smirnoff.com/en-gb/products/vodkas-and-flavors/cherry-drop",
        "catalogue_source": "Vodka and Rum",
        "catalogue_number": 112,
        "is_published": true
      },
      {
        "id": "bacardi-carta-blanca",
        "name": "Bacardí Carta Blanca",
        "category": "Other",
        "subtype": "Rum",
        "brand": "Bacardí",
        "origin": "Santiago de Cuba, Cuba",
        "description": "A light, aromatic white rum with delicate floral and fruity notes, almond and vanilla, and a clean, dry finish.",
        "image_url": "https://d323g1xugy1rkz.cloudfront.net/wp-content/uploads/2024/10/30150247/Bacardi_CartaBlanca_IPX_70CL-menu.png",
        "official_tags": ["light", "floral", "fruity", "almond", "vanilla", "clean", "dry"],
        "flavour_source_url": "https://www.bacardi.com/rum/carta-blanca/",
        "origin_source_url": "https://www.bacardilimited.com/our-company/our-history/",
        "image_source_url": "https://www.bacardi.com/rum/carta-blanca/",
        "catalogue_source": "Vodka and Rum",
        "catalogue_number": 113,
        "is_published": true
      }
    ]$saturated_catalogue$::jsonb
  ) as item(
    id text,
    name text,
    category text,
    subtype text,
    brand text,
    origin text,
    description text,
    image_url text,
    official_tags text[],
    flavour_source_url text,
    origin_source_url text,
    image_source_url text,
    catalogue_source text,
    catalogue_number integer,
    is_published boolean
  )
)
insert into public.beverages (
  id,
  name,
  category,
  subtype,
  brand,
  origin,
  description,
  image_url,
  official_tags,
  flavour_source_url,
  origin_source_url,
  image_source_url,
  catalogue_source,
  catalogue_number,
  is_published
)
select
  id,
  name,
  category,
  subtype,
  brand,
  origin,
  description,
  image_url,
  official_tags,
  flavour_source_url,
  origin_source_url,
  image_source_url,
  catalogue_source,
  catalogue_number,
  is_published
from catalogue
on conflict (id) do update
set
  name = excluded.name,
  category = excluded.category,
  subtype = excluded.subtype,
  brand = excluded.brand,
  origin = excluded.origin,
  description = excluded.description,
  image_url = excluded.image_url,
  official_tags = excluded.official_tags,
  flavour_source_url = excluded.flavour_source_url,
  origin_source_url = excluded.origin_source_url,
  image_source_url = excluded.image_source_url,
  catalogue_source = excluded.catalogue_source,
  catalogue_number = excluded.catalogue_number,
  is_published = excluded.is_published,
  updated_at = timezone('utc', now());

update public.beverages
set
  category = 'Other',
  subtype = 'Rum',
  updated_at = timezone('utc', now())
where id = 'malibu-coconut-rum';
